add_newline = true

# Change the default prompt format
format = """\
[â•­â•´](238)$env_var\
$all[â•°â”€](238)$character"""

# Change the default prompt characters
[character]
success_symbol = "[ï€Œ](green)"
error_symbol = "[ï‘§](red)"




# Shows current directory
[directory]
#truncation_length = 10
#truncation_symbol = "â€¦/"
#home_symbol = " ~"
fish_style_pwd_dir_length = 0
#read_only_style = "197"
#format = "[$path]($style)[$read_only]($read_only_style) "



# Shows kubernetes context and namespace
[kubernetes]
format = '[ó±ƒ¾ $context\($namespace\)](bold red )'
disabled = false

[terraform]
format = '[ğŸğŸ’¨ $version$workspace]($style) '

[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = 'bold blue'
symbol = 'ğŸ…° '
#[aws.profile_aliases]
#CompanyGroupFrobozzOnCallAccess = 'Frobozz'
